TwinCitiesCodeCamp/Models/Schedule/ScheduleModel.cs
namespace TwinCitiesCodeCamp.Models.Schedule
{
	public sealed class ScheduleModel { }
}

TwinCitiesCodeCamp/Controllers/ScheduleController.cs
using System.Web.Mvc;
using TwinCitiesCodeCamp.Models.Schedule;

namespace TwinCitiesCodeCamp.Controllers
{
	public sealed class ScheduleController
		: Controller
	{
		public ActionResult Spring2015()
		{
			return this.View(new ScheduleModel());
		}

		public ActionResult Fall2014()
		{
			return this.View(new ScheduleModel());
		}

		public ActionResult Spring2014()
		{
			return this.View(new ScheduleModel());
		}

		public ActionResult Fall2013()
		{
			return this.View(new ScheduleModel());
		}

		public ActionResult Spring2013()
		{
			return this.View(new ScheduleModel());
		}

		public ActionResult Fall2012()
		{
			return this.View(new ScheduleModel());
		}

		public ActionResult Spring2012()
		{
			return this.View(new ScheduleModel());
		}

		public ActionResult Fall2011()
		{
			return this.View(new ScheduleModel());
		}

		public ActionResult Spring2011()
		{
			return this.View(new ScheduleModel());
		}

		public ActionResult Fall2010()
		{
			return this.View(new ScheduleModel());
		}

		public ActionResult Spring2010()
		{
			return this.View(new ScheduleModel());
		}

		public ActionResult Fall2009()
		{
			return this.View(new ScheduleModel());
		}

		public ActionResult Spring2009()
		{
			return this.View(new ScheduleModel());
		}

		public ActionResult Fall2008()
		{
			return this.View(new ScheduleModel());
		}

		public ActionResult Spring2008()
		{
			return this.View(new ScheduleModel());
		}

		public ActionResult Fall2007()
		{
			return this.View(new ScheduleModel());
		}

		public ActionResult Spring2007()
		{
			return this.View(new ScheduleModel());
		}

		public ActionResult Fall2006()
		{
			return this.View(new ScheduleModel());
		}
	}
}

TwinCitiesCodeCamp/Controllers/SessionsController.cs
using System.Web.Mvc;
using TwinCitiesCodeCamp.Models.Sessions;

namespace TwinCitiesCodeCamp.Controllers
{
	public sealed class SessionsController
		: Controller
	{
		public ActionResult Spring2015()
		{
			return this.View(new SessionsModel());
		}

		public ActionResult Fall2014()
		{
			return this.View(new SessionsModel());
		}

		public ActionResult Spring2014()
		{
			return this.View(new SessionsModel());
		}

		public ActionResult Fall2013()
		{
			return this.View(new SessionsModel());
		}

		public ActionResult Spring2013()
		{
			return this.View(new SessionsModel());
		}

		public ActionResult Fall2012()
		{
			return this.View(new SessionsModel());
		}

		public ActionResult Spring2012()
		{
			return this.View(new SessionsModel());
		}

		public ActionResult Fall2011()
		{
			return this.View(new SessionsModel());
		}

		public ActionResult Spring2011()
		{
			return this.View(new SessionsModel());
		}

		public ActionResult Fall2010()
		{
			return this.View(new SessionsModel());
		}

		public ActionResult Spring2010()
		{
			return this.View(new SessionsModel());
		}

		public ActionResult Fall2009()
		{
			return this.View(new SessionsModel());
		}

		public ActionResult Spring2009()
		{
			return this.View(new SessionsModel());
		}

		public ActionResult Fall2008()
		{
			return this.View(new SessionsModel());
		}

		public ActionResult Spring2008()
		{
			return this.View(new SessionsModel());
		}

		public ActionResult Fall2007()
		{
			return this.View(new SessionsModel());
		}

		public ActionResult Spring2007()
		{
			return this.View(new SessionsModel());
		}

		public ActionResult Fall2006()
		{
			return this.View(new SessionsModel());
		}
	}
}

TwinCitiesCodeCamp/Controllers/SpeakersController.cs
using System.Web.Mvc;
using TwinCitiesCodeCamp.Models.Speakers;

namespace TwinCitiesCodeCamp.Controllers
{
	public sealed class SpeakersController
		: Controller
	{
		public ActionResult CallForSpeakers()
		{
			return this.View(new SpeakersModel());
		}

		public ActionResult Spring2015()
		{
			return this.View(new SpeakersModel());
		}

		public ActionResult Fall2014()
		{
			return this.View(new SpeakersModel());
		}

		public ActionResult Spring2014()
		{
			return this.View(new SpeakersModel());
		}

		public ActionResult Fall2013()
		{
			return this.View(new SpeakersModel());
		}

		public ActionResult Spring2013()
		{
			return this.View(new SpeakersModel());
		}

		public ActionResult Fall2012()
		{
			return this.View(new SpeakersModel());
		}

		public ActionResult Spring2012()
		{
			return this.View(new SpeakersModel());
		}

		public ActionResult Fall2011()
		{
			return this.View(new SpeakersModel());
		}

		public ActionResult Spring2011()
		{
			return this.View(new SpeakersModel());
		}

		public ActionResult Fall2010()
		{
			return this.View(new SpeakersModel());
		}

		public ActionResult Spring2010()
		{
			return this.View(new SpeakersModel());
		}

		public ActionResult Fall2009()
		{
			return this.View(new SpeakersModel());
		}

		public ActionResult Spring2009()
		{
			return this.View(new SpeakersModel());
		}

		public ActionResult Fall2008()
		{
			return this.View(new SpeakersModel());
		}

		public ActionResult Spring2008()
		{
			return this.View(new SpeakersModel());
		}

		public ActionResult Fall2007()
		{
			return this.View(new SpeakersModel());
		}
	}
}

TwinCitiesCodeCamp/Views/Schedule/Fall2006.cshtml
<h1>Fall 2006 - Schedule</h1>
<table border="1" align="center">
    <thead align="center">
        <tr>
            <td>
                Time
            </td>
            <td>
                Seminar Room
            </td>
            <td>
                Classroom 3
            </td>
            <td>
                Classroom 7
            </td>
            <td>
                Classroom 1
            </td>
        </tr>
    </thead>
    <tr align="center">
        <td>
            8:30 - 9:00
        </td>
        <td colspan="4">
            Doors Open - Continental Breakfast (sponsored by <a href="http://www.ilmservice.com">
                ILM Services
            </a>)
        </td>
    </tr>
    <tr align="center">
        <td align="center">
            9:00 - 10:00
        </td>
        <td>
            <a href="@Url.Content("~/Sessions/Fall2006#s2")">Improving your Forms with WPF</a><br />
            <i>Chris Sutton</i>
        </td>
        <td>
            <a href="@Url.Content("~/Sessions/Fall2006#s19")">Object/Relational Mapping with Hibernate</a><br />
            <i>Bob McCune</i>
        </td>
        <td>
            <a href="@Url.Content("~/Sessions/Fall2006#s3")">SharePoint as a Development Platform</a><br />
            <i>Neil Iverson</i>
        </td>
        <td>
            <a href="@Url.Content("~/Sessions/Fall2006#s4")">Managing Memory in a Managed World</a><br />
            <i>Chad Yost</i>
        </td>
    </tr>
    <tr align="center">
        <td align="center">
            10:00 - 11:00
        </td>
        <td>
            <a href="@Url.Content("~/Sessions/Fall2006#s11")">
                Model View Presenter Design and Implementation Within the
                .NET Framework 2.0
            </a><br />
            <i>Chase Thomas</i>
        </td>
        <td>
            <a href="@Url.Content("~/Sessions/Fall2006#s13")">Quick and Dirty Functional Testing with Selenium</a><br />
            <i>Steve Peterson</i>
        </td>
        <td>
            <a href="@Url.Content("~/Sessions/Fall2006#s7")">SQL Server Integration Services - Performance Tips and Tricks</a><br />
            <i>David Baldauff</i>
        </td>
        <td>
            <a href="@Url.Content("~/Sessions/Fall2006#s25")">The State of Languages on the CLR</a><br />
            <i>Jason Bock</i>
        </td>
    </tr>
    <tr align="center">
        <td align="center">
            11:00 - 12:00
        </td>
        <td>
            <a href="@Url.Content("~/Sessions/Fall2006#s26")">Build Innovative Applications Using Amazon Web Services</a><br />
            <i>Jinesh Varia</i>
        </td>
        <td>
            <a href="@Url.Content("~/Sessions/Fall2006#s21")">Developing Speech Enabled Applications with .NET</a><br />
            <i>Michael Dunn</i>
        </td>
        <td>
            <a href="@Url.Content("~/Sessions/Fall2006#s9")">
                Web Parts Design for SharePoint: The Difference Between
                2003 and 2007 HOL
            </a><br />
            <i>Jim Ferguson</i>
        </td>
        <td>
            <a href="@Url.Content("~/Sessions/Fall2006#s23")">Generics Support in .NET 2.0</a><br />
            <i>Doug Nelson</i>
        </td>
    </tr>
    <tr align="center">
        <td>
            12:00 - 1:00
        </td>
        <td colspan="4">
            Lunch (sponsored by <a href="http://www.magenic.com">Magenic</a>)
        </td>
    </tr>
    <tr align="center">
        <td align="center">
            1:00 - 2:00
        </td>
        <td>
            <a href="@Url.Content("~/Sessions/Fall2006#s17")">
                Creating High Performance/High Impact Windows Forms Using
                Custom Controls In .NET 2.0
            </a><br />
            <i>Cory Smith</i>
        </td>
        <td>
            <a href="@Url.Content("~/Sessions/Fall2006#s16")">Utilizing .NET Cryptography</a><br />
            <i>Robert Boedigheimer</i>
        </td>
        <td>
            <a href="@Url.Content("~/Sessions/Fall2006#s10")">SQL Server 2005 and Async Calls</a><br />
            <i>Ron Hovland</i>
        </td>
        <td>
            <a href="@Url.Content("~/Sessions/Fall2006#s8")">Introduction to Programming with the VSTS SDK</a><br />
            <i>Michael Ruminer</i>
        </td>
    </tr>
    <tr align="center">
        <td align="center">
            2:00 - 3:00
        </td>
        <td>
            <a href="@Url.Content("~/Sessions/Fall2006#s18")">XboxFriends...Under The Covers</a><br />
            <i>Cory Smith</i>
        </td>
        <td>
            <a href="@Url.Content("~/Sessions/Fall2006#s15")">ASP.NET 2.0 Configuration Files</a><br />
            <i>Robert Boedigheimer</i>
        </td>
        <td>
            <a href="@Url.Content("~/Sessions/Fall2006#s12")">Building Reusable Business Processes with BizTalk Server</a><br />
            <i>Andy Morrison</i>
        </td>
        <td>
            <a href="@Url.Content("~/Sessions/Fall2006#s27")">Integrating Ruby on Rails and .NET</a><br />
            <i>Jacob Good</i>
        </td>
    </tr>
    <tr align="center">
        <td align="center">
            3:00 - 4:00
        </td>
        <td>
            <a href="@Url.Content("~/Sessions/Fall2006#s20")">
                Implementing an Automated Build and Continuous Integration
                Process for .NET Development Projects
            </a><br />
            <i>Mike Jones</i>
        </td>
        <td>
            <a href="@Url.Content("~/Sessions/Fall2006#s1")">The Mobile Client Software Factory</a><br />
            <i>Kenny Goers</i>
        </td>
        <td>
            <a href="@Url.Content("~/Sessions/Fall2006#s24")">Securing Web Services in WCF</a><br />
            <i>Jeff Knutson</i>
        </td>
        <td>
            <a href="@Url.Content("~/Sessions/Fall2006#s5")">Foundations of Ajax</a><br />
            <i>Nathaniel T. Schutta</i>
        </td>
    </tr>
    <tr align="center">
        <td align="center">
            4:00 - 5:00
        </td>
        <td>
            <a href="@Url.Content("~/Sessions/Fall2006#s14")">Building Applications with CSLA .NET</a><br />
            <i>Rockford Lhotka</i>
        </td>
        <td>
            <a href="@Url.Content("~/Sessions/Fall2006#s6")">REST and its Discontents</a><br />
            <i>Luke Francl</i>
        </td>
        <td>
            <a href="@Url.Content("~/Sessions/Fall2006#s28")">How Does WCF and 3.0 Impact My Coding Techniques?</a><br />
            <i>Scott Yokiel</i>
        </td>
        <td>
            <a href="@Url.Content("~/Sessions/Fall2006#s22")">JRuby: Ruby on the JVM</a><br />
            <i>Charles Nutter</i>
        </td>
    </tr>
    <tr align="center">
        <td>
            5:00 - 5:15
        </td>
        <td colspan="4">
            Closing Remarks and Prizes
        </td>
    </tr>
</table>

TwinCitiesCodeCamp/Views/Schedule/Fall2014.cshtml
<h1>
    Fall 2014 - Schedule
</h1>
<p>
    Note: The schedule is subject to change up until the day of the event. You can rate the sessions <a href="http://speakr.cc/" target="_blank">here</a>.
</p>
<h2>
    Saturday, 10/4
</h2>
<table border="1" align="center">
    <thead align="center">
        <tr>
            <td>
                Time
            </td>
            <td>
                Rapson 100
            </td>
            <td>
                Rapson 31
            </td>
            <td>
                Rapson 45
            </td>
            <td>
                Rapson 54
            </td>
            <td>
                Rapson 56
            </td>
            <td>
                Keller 3-115
            </td>
            <td>
                Keller 3-125
            </td>
        </tr>
    </thead>
    <tr align="center">
        <td>
            8:30 - 9:15
        </td>
        <td colspan="7">
            Registration Starts + Continental Breakfast<br />
        </td>
    </tr>
    <tr align="center">
        <td>
            9:15 - 9:30
        </td>
        <td colspan="7">
            Welcome and Introduction From TCCC Leadership Team in Rapson 100
        </td>
    </tr>
    <tr align="center">
        <td align="center">
            9:30 - 10:30
        </td>
        <td>
            @Html.ActionLink("High Performance JavaScript", "Fall2014", "Sessions", null, null, "s10", null, null)<br />
            <i>@Html.ActionLink("Md khan", "Fall2014", "Speakers", null, null, "sp10", null, null)</i>
        </td>
        <td>
            @Html.ActionLink("Next Generation Web Applications With React", "Fall2014", "Sessions", null, null, "s18", null, null)<br />
            <i>@Html.ActionLink("Eric Brandes", "Fall2014", "Speakers", null, null, "sp18", null, null)</i>
        </td>
        <td>
            @Html.ActionLink("Building SPAs with the MEAN Stack", "Fall2014", "Sessions", null, null, "s8", null, null)<br />
            <i>@Html.ActionLink("Shannon Hofer", "Fall2014", "Speakers", null, null, "sp8", null, null)</i>
        </td>
        <td>
            @Html.ActionLink("Call of the Raven: RavenDB for the .NET Developer", "Fall2014", "Sessions", null, null, "s35", null, null)<br />
            <i>@Html.ActionLink("Judah Himango", "Fall2014", "Speakers", null, null, "sp35", null, null)</i>
        </td>
        <td>
            @Html.ActionLink("Cross-Platform Mobile with Xamarin.Forms", "Fall2014", "Sessions", null, null, "s6", null, null)<br />
            <i>@Html.ActionLink("Jeremy Ellis", "Fall2014", "Speakers", null, null, "sp6", null, null)</i>
        </td>
        <td>
            @Html.ActionLink("Demystifying TypeScript", "Fall2014", "Sessions", null, null, "s3", null, null)<br />
            <i>@Html.ActionLink("Kamran Ayub", "Fall2014", "Speakers", null, null, "sp3", null, null)</i>
        </td>
        <td>
            @Html.ActionLink("Securing TodoMVC Using the Web Cryptography API", "Fall2014", "Sessions", null, null, "s15", null, null)<br />
            <i>@Html.ActionLink("Kevin Hakanson", "Fall2014", "Speakers", null, null, "sp15", null, null)</i>
        </td>
    </tr>
    <tr align="center">
        <td>
            10:30 - 10:45
        </td>
        <td colspan="7">
            Break
        </td>
    </tr>
    <tr align="center">
        <td>
            10:45 - 11:45
        </td>
        <td>
            @Html.ActionLink("Getting Started with node.js", "Fall2014", "Sessions", null, null, "s4", null, null)<br />
            <i>@Html.ActionLink("Richard Brantley", "Fall2014", "Speakers", null, null, "sp4", null, null)</i>
        </td>
        <td>
            @Html.ActionLink("When Learning Stops: Recovering from an Expert Beginner", "Fall2014", "Sessions", null, null, "s21", null, null)<br />
            <i>@Html.ActionLink("Zac Harlan", "Fall2014", "Speakers", null, null, "sp21", null, null) and @Html.ActionLink("Keith Dahlby", "Fall2014", "Speakers", null, null, "sp22", null, null)</i>
        </td>
        <td>
            @Html.ActionLink("Oculus Rift and the Impending VR Revolution", "Fall2014", "Sessions", null, null, "s20", null, null)<br />
            <i>@Html.ActionLink("Justin Chase", "Fall2014", "Speakers", null, null, "sp20", null, null)</i>
        </td>
        <td>
            @Html.ActionLink("Building a Modern Windows App", "Fall2014", "Sessions", null, null, "s34", null, null)<br />
            <i>@Html.ActionLink("Brent Edwards", "Fall2014", "Speakers", null, null, "sp34", null, null)</i>
        </td>
        <td>
            @Html.ActionLink("Introduction to Swift for iOS", "Fall2014", "Sessions", null, null, "s19", null, null)<br />
            <i>@Html.ActionLink("Joe Koletar", "Fall2014", "Speakers", null, null, "sp19", null, null)</i>
        </td>
        <td>
            @Html.ActionLink("Intro to Puppet", "Fall2014", "Sessions", null, null, "s17", null, null)<br />
            <i>@Html.ActionLink("Jason Clifford", "Fall2014", "Speakers", null, null, "sp17", null, null)</i>
        </td>
        <td>
            @Html.ActionLink("Acceptance Test Driven Development", "Fall2014", "Sessions", null, null, "s16", null, null)<br />
            <i>@Html.ActionLink("Benoy John", "Fall2014", "Speakers", null, null, "sp16", null, null)</i>
        </td>
    </tr>
    <tr align="center">
        <td>
            11:45 - 12:45
        </td>
        <td colspan="7">
            Lunch Break, Pizza Sponsored by <a href="http://www.teksystems.com/" target="_blank">TEK Systems</a><br />
        </td>
    </tr>
    <tr align="center">
        <td align="center">
            12:45 - 1:45
        </td>
        <td>
            @Html.ActionLink("Angular, TypeScript and Project Katana", "Fall2014", "Sessions", null, null, "s24", null, null)<br />
            <i>@Html.ActionLink("Justin Wendlandt", "Fall2014", "Speakers", null, null, "sp25", null, null)</i>
        </td>
        <td>
            @Html.ActionLink("NoSQL Done Right: Introduction to Couchbase", "Fall2014", "Sessions", null, null, "s12", null, null)<br />
            <i>@Html.ActionLink("Nick Melnick", "Fall2014", "Speakers", null, null, "sp12", null, null)</i>
        </td>
        <td>
            @Html.ActionLink("Intro to Translation: From Zero to Implementation", "Fall2014", "Sessions", null, null, "s26", null, null)<br />
            <i>@Html.ActionLink("Austin Thompson", "Fall2014", "Speakers", null, null, "sp27", null, null)</i>
        </td>
        <td>
            @Html.ActionLink("Managing the .NET Compiler", "Fall2014", "Sessions", null, null, "s31", null, null)<br />
            <i>@Html.ActionLink("Jason Bock", "Fall2014", "Speakers", null, null, "sp31", null, null)</i>
        </td>
        <td>
            @Html.ActionLink("Cross-Platform Mobile Development with Titanium and the Appcelerator Platform", "Fall2014", "Sessions", null, null, "s9", null, null)<br />
            <i>@Html.ActionLink("Vince Bullinger", "Fall2014", "Speakers", null, null, "sp9", null, null)</i>
        </td>
        <td>
            @Html.ActionLink("DevOps with Elastic Beanstalk", "Fall2014", "Sessions", null, null, "s27", null, null)<br />
            <i>@Html.ActionLink("Scott Colestock", "Fall2014", "Speakers", null, null, "sp28", null, null)</i>
        </td>
        <td>
            @Html.ActionLink("One Delegate to Rule Them All: Understanding OWIN", "Fall2014", "Sessions", null, null, "s29", null, null)<br />
            <i>@Html.ActionLink("Keith Dahlby", "Fall2014", "Speakers", null, null, "sp22", null, null)</i>
        </td>
    </tr>
    <tr align="center">
        <td>
            1:45 - 2:00
        </td>
        <td colspan="7">
            Break With Afternoon Snacks<br />
        </td>
    </tr>
    <tr align="center">
        <td align="center">
            2:00 - 3:00
        </td>
        <td>
            @Html.ActionLink("Evolving From REST to Hypermedia Designs", "Fall2014", "Sessions", null, null, "s33", null, null)<br />
            <i>@Html.ActionLink("Philip Nelson", "Fall2014", "Speakers", null, null, "sp33", null, null)</i>
        </td>
        <td>
            @Html.ActionLink("Polyglot Persistence", "Fall2014", "Sessions", null, null, "s30", null, null)<br />
            <i>@Html.ActionLink("Ayende Rahien", "Fall2014", "Speakers", null, null, "sp30", null, null)</i>
        </td>
        <td>
            @Html.ActionLink("Stylesheet Retrospective", "Fall2014", "Sessions", null, null, "s22", null, null)<br />
            <i>@Html.ActionLink("Josh Renner", "Fall2014", "Speakers", null, null, "sp23", null, null)</i>
        </td>
        <td>
            @Html.ActionLink("Talking to Cortana: How to Set Up and Use Voice in Windows Phone", "Fall2014", "Sessions", null, null, "s5", null, null)<br />
            <i>@Html.ActionLink("Carl Schweitzer", "Fall2014", "Speakers", null, null, "sp5", null, null)</i>
        </td>
        <td>
            @Html.ActionLink("From App Studio to Mobile Services to Xamarin - Connecting the Dots", "Fall2014", "Sessions", null, null, "s28", null, null)<br />
            <i>@Html.ActionLink("Mike Benkovich", "Fall2014", "Speakers", null, null, "sp1", null, null)</i>
        </td>
        <td>
            @Html.ActionLink("Developing Highly-Scalable Apps for the Azure Cloud", "Fall2014", "Sessions", null, null, "s13", null, null)<br />
            <i>@Html.ActionLink("Brian Bosak", "Fall2014", "Speakers", null, null, "sp13", null, null)</i>
        </td>
        <td>
            @Html.ActionLink("Intro To Nancy", "Fall2014", "Sessions", null, null, "s11", null, null)<br />
            <i>@Html.ActionLink("Joel Kaufmann", "Fall2014", "Speakers", null, null, "sp11", null, null)</i>
        </td>
    </tr>
    <tr align="center">
        <td>
            3:00 - 3:15
        </td>
        <td colspan="7">
            Break
        </td>
    </tr>
    <tr align="center">
        <td align="center">
            3:15 - 4:15
        </td>
        <td>
            @Html.ActionLink("Doing Open Source the Right Way", "Fall2014", "Sessions", null, null, "s25", null, null)<br />
            <i>@Html.ActionLink("Charles Oliver Nutter", "Fall2014", "Speakers", null, null, "sp26", null, null)</i>
        </td>
        <td>
            @Html.ActionLink("Avoiding Hacker Tricks", "Fall2014", "Sessions", null, null, "s1", null, null)<br />
            <i>@Html.ActionLink("Mike Benkovich", "Fall2014", "Speakers", null, null, "sp1", null, null)</i>
        </td>
        <td>
            @Html.ActionLink("Eradicate \"Not Invented Here\" - Libraries and Services for Common Application Needs", "Fall2014", "Sessions", null, null, "s32", null, null)<br />
            <i>@Html.ActionLink("Mike Marshall", "Fall2014", "Speakers", null, null, "sp32", null, null)</i>
        </td>
        <td>
            @Html.ActionLink("Intro to Kinect HD for Windows", "Fall2014", "Sessions", null, null, "s23", null, null)<br />
            <i>@Html.ActionLink("Travis Feirtag", "Fall2014", "Speakers", null, null, "sp24", null, null)</i>
        </td>
        <td>
            @Html.ActionLink("Low Flying Ravens - How Voron is Built", "Fall2014", "Sessions", null, null, "s14", null, null)<br />
            <i>@Html.ActionLink("Ayende Rahien", "Fall2014", "Speakers", null, null, "sp30", null, null)</i>
        </td>
        <td>
            @Html.ActionLink("Lightning Talks", "Fall2014", "Sessions", null, null, "s7", null, null)<br />
            <i>Hosted by @Html.ActionLink("Jake Good", "Fall2014", "Speakers", null, null, "sp7", null, null)</i>
        </td>
        <td>
            @Html.ActionLink("Give Your App Some Global Appeal", "Fall2014", "Sessions", null, null, "s2", null, null)<br />
            <i>@Html.ActionLink("Brandon H", "Fall2014", "Speakers", null, null, "sp2", null, null)</i>
        </td>
    </tr>
    <tr align="center">
        <td>
            4:15 - 4:45
        </td>
        <td colspan="7">
            Closing Remarks and Prize Giveaway in Rapson 100
        </td>
    </tr>
</table>